### ISSUE TITLE
安装GPU驱动出现问题

### ISSUE THREAD

**Issue by whuanle** [IntelligentEdgeFabric/gpu-installer#8]
```
NVIDIA_DRIVER_VERSION=430.40  NVIDIA_DRIVER_DOWNLOAD_URL=http://cn.download.nvidia.com/XFree86/Linux-x86_64/430.40/NVIDIA-Linux-x86_64-430.40.run bash nvidia-gpu-installer.sh install -y
```
![image](https://user-images.githubusercontent.com/2189761/62999012-bb1f9f00-be9f-11e9-8bf6-a7deffc84208.png)

**Comment by whuanle** [comment]
![image](https://user-images.githubusercontent.com/2189761/62999530-52d1bd00-bea1-11e9-8e58-08fa89902adf.png)
![image](https://user-images.githubusercontent.com/2189761/62999547-5feeac00-bea1-11e9-9d7d-9ee0a1ea8ac8.png)

**Comment by llhuii** [comment]
Nouveau 驱动已经被加载了，导致无法加载nvidia驱动。
禁用nouveau可以参考nvidia官方文档https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-nouveau
记得重启机器.

**Comment by whuanle** [comment]
安装成功啦，十分感谢 @llhuii
